name: flutter_blue_plus
description: Flutter plugin for connecting and communicationg with Bluetooth Low Energy devices, on Android and iOS
version: 1.5.0
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  protobuf: ^2.1.0
  rxdart: ^0.27.7
  collection: ^1.16.0
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.boskokg.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
      ios:
        pluginClass: FlutterBluePlusPlugin
      macos:
        pluginClass: FlutterBluePlusPlugin
      windows:
        pluginClass: FlutterBluePlusPluginCApi
